### ISSUE TITLE
cant click anything

### ISSUE THREAD

**Issue by squeaks1811** [ASMRoyal/Eulen#3]
after i inject it i can click anything on the menu how do i use it

**Comment by usgvva** [comment]
same for me

**Comment by ASMRoyal** [comment]
> after i inject it i can click anything on the menu how do i use it

Please join my discord and open a ticket.

**Comment by ASMRoyal** [comment]
**troubleshooter is now available** [here](https://github.com/ASMRoyal/Eulen/releases/tag/Troubleshooter)
